version: "3.7"

x-service-base: &service-base
  image: cloudreactor-aws-setup-wizard
  build:
    context: ./
  volumes:
    - .:/usr/app
  env_file:
    - .env

x-dev-base: &dev-base
  <<: *service-base
  image:  cloudreactor-aws-setup-wizard_dev
  build:
    context: ./
    dockerfile: Dockerfile-dev

services:
  make_template:
    <<: *service-base

  wizard:
    <<: *service-base
    entrypoint: python src/wizard.py
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
    volumes:
      - .:/usr/app
      - ~/.aws/:/root/.aws:ro

  shell:
    <<: *service-base
    entrypoint: bash

  flake8:
    <<: *dev-base

  mypy:
    <<: *dev-base
    entrypoint: ["mypy", "--config-file", "src/mypy.ini", "src"]

  safety:
    <<: *dev-base
    entrypoint: ["safety", "check"]

  dev-shell:
    <<: *dev-base
    command: bash
