FROM cloudreactor-aws-setup-wizard

COPY ./requirements.txt .
COPY ./dev-requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt -r dev-requirements.txt

ENTRYPOINT ["flake8", "--config", "src/.flake8", "src"]

