version: "3.7"

x-service-base: &service-base
  image: aws-setup-wizard
  build:
    context: ./
  volumes:
    - ./saved_state:/usr/app/saved_state
    # These are here so we run the wizard with the latest source but without
    # rebuilding the Docker image.
    - ./src:/usr/app/src
    - ./templates:/usr/app/templates
  env_file:
    - .env

x-dev-base: &dev-base
  <<: *service-base
  image:  aws-setup-wizard_dev
  build:
    context: ./
    dockerfile: Dockerfile-dev

services:
  make_template:
    <<: *service-base

  wizard:
    <<: *service-base
    entrypoint: python src/wizard.py

    # environment:
     # AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

     # # To pass in access key / secret
     # AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
     # AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

     # AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}

     # To use a AWS profile in ~/.aws
     # AWS_PROFILE: ${AWS_PROFILE}
    volumes:
      - .:/usr/app
      # To use a AWS profile in ~/.aws
      #- /home/jtsay/.aws/:/root/.aws/

  shell:
    <<: *service-base
    entrypoint: bash

  # To update requirements.txt:
  # docker compose run --rm pip-compile > requirements.txt
  pip-compile: &pip-compile-base
    image: aws-setup-wizard
    entrypoint: pip-compile --allow-unsafe --generate-hashes --output-file=-

  # To update dev-requirements.txt:
  # docker compose run --rm pip-compile-dev > dev-requirements.txt
  pip-compile-dev:
    <<: *pip-compile-base
    image: aws-setup-wizard_dev
    build:
      dockerfile: Dockerfile-dev
    command: dev-requirements.in

  flake8:
    <<: *dev-base

  mypy:
    <<: *dev-base
    entrypoint: ["mypy", "--config-file", "src/mypy.ini", "src"]

  safety:
    <<: *dev-base
    entrypoint: ["safety", "check"]

  dev-shell:
    <<: *dev-base
    entrypoint: bash
