name: CI
on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - uses: abatilo/actions-poetry@v2.1.4
    - name: Install Dependencies
      run: poetry install
    - name: flake8
      run: poetry run flake8
    - name: isort
      run: poetry run isort --verbose --ignore-whitespace cloudreactor_aws_setup_wizard
    - name: mypy
      run: "poetry run mypy -m cloudreactor_aws_setup_wizard || true"
    - name: Check for library vulnerabilities with pip-audit
      run: poetry run pip_audit -r requirements.txt
    - name: Print final message
      run: "echo Complete"
