name: CI
on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt -r dev-requirements.txt

    - name: flake8
      run: "flake8 src"
      env:
        PYTHONPATH: src

    - name: mypy
      run: "mypy src || true"
      env:
        PYTHONPATH: src

    - name: Print final message
      run: "echo Complete"
