name: Tests
on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r generator/requirements.txt
        pip install -r generator/dev-requirements.txt

    - name: Syntax check lambda functions with flake8
      run: "flake8 --config src/python/.flake8 src/python"
      env:
        PYTHONPATH: src/python

    - name: Syntax check utilities with flake8
      run: "flake8 --config generator/.flake8 generator"
      env:
        PYTHONPATH: generator

    - name: Type check lambda functions with mypy
      run: "mypy src/python"
      env:
        PYTHONPATH: src/python

    - name: Make role template
      run: "python generator/make_template.py"

    - name: Print final message
      run: "echo Complete"
